"""add unique user widget constraint

Revision ID: b0c59a8f9070
Revises: da6c39420cae
Create Date: 2026-09-09 22:26:14.633985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c59a8f9070'
down_revision: Union[str, Sequence[str], None] = 'da6c39420cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_widget', 'widget_preferences', ['user_id', 'widget_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_widget', 'widget_preferences', type_='unique')
    # ### end Alembic commands ###
